name: Azure App Service Backend API CI/CD

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

env:
    AZURE_WEBAPP_NAME: todo-backend-app-2024
    AZURE_RESOURCE_GROUP: todo-api-rg

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'

        - name: Install dependencies
          run: go mod tidy

        - name: Build the backend API
          run: go build -o main .
        
        - name: Upload build artifact
          uses: actions/upload-artifact@v4
          with:
            name: todo-api-backend-build
            path: main

    unit-test:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'

        - name: Run unit tests
          run: go test -coverprofile=coverage.out

        - name: Upload coverage report
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report
            path: coverage.out


    deploy:
        runs-on: ubuntu-latest
        needs: [build, unit-test]
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'

        - name: Install dependencies
          run: go mod download

        - name: Build the backend API
          run: go build -o main .

        - name: Create deployment package
          run: |
            mkdir -p deployment
            cp main deployment/
            cp -r handlers deployment/
            cp -r models deployment/
            cp -r database deployment/
            cp -r middleware deployment/
            cp go.mod deployment/
            cp go.sum deployment/
            cp startup.sh deployment/
            chmod +x deployment/startup.sh

        - name: Deploy backend API to Azure App Service
          uses: azure/webapps-deploy@v3
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            package: ./deployment
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

        - name: Azure logout
          run: |
            az logout